### ISSUE TITLE
Predefined ignored repos for clean and update

### ISSUE THREAD

**Issue by Matt-Gleich** [Matt-Gleich/fgh#27]
## Description

Allow the user to define in a config file the repos to ignore for the following commands:

* clean
* pull
* update

Config syntax should look like this:

```yaml
- OWNER:
    - NAME:
      clean: false
      pull: true
      update: true
    - NAME
- OWNER:
  clean: true
  pull: true
  update: true
- NAME 
```
